# Generated by Django 3.2.7 on 2021-11-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='durations_service_time',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Длительность [час]'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Стоимость [₽]'),
        ),
    ]
