# Generated by Django 3.2.7 on 2021-11-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veld', '0002_auto_20211123_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ('name',), 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veld.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='service',
            name='durations_service_time',
            field=models.PositiveIntegerField(verbose_name='Длительность [мин]'),
        ),
    ]
